#!/bin/sh

set -x -eo pipefail

###
# Installations
###

apk add --no-cache gradle=${GRADLE_VERSION}

###
# Cleaning image
###

apk del --no-cache curl

###
# CIS Hardening
###

chmod 0600 /etc/shadow

touch /etc/login.defs
chmod 0444 /etc/login.defs